from django.contrib.auth import views as auth_views
from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("health/", views.health, name="health"),
    path("register/", views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("play/", views.dashboard, name="dashboard"),
    path("profile/", views.profile, name="profile"),
    path("settings/", views.settings, name="settings"),
    path("pets/new/", views.create_pet, name="create_pet"),
    path("pets/<int:pet_id>/select/", views.select_pet, name="select_pet"),
    path("pets/action/<str:action>/", views.pet_action, name="pet_action"),
    path("shop/", views.shop, name="shop"),
    path("shop/buy/<int:item_id>/", views.buy_item, name="buy_item"),
    path("shop/wearables/", views.wearable_shop, name="wearable_shop"),
    path("shop/wearables/buy/<int:wearable_id>/", views.buy_wearable, name="buy_wearable"),
    path("inventory/", views.inventory, name="inventory"),
    path("inventory/use/<int:inventory_id>/", views.use_item, name="use_item"),
    path("wardrobe/", views.wardrobe, name="wardrobe"),
    path("wardrobe/equip/<int:owned_id>/", views.equip_wearable, name="equip_wearable"),
    path("wardrobe/unequip/<int:equipped_id>/", views.unequip_wearable, name="unequip_wearable"),
    path("wardrobe/sell/<int:owned_id>/", views.sell_wearable, name="sell_wearable"),
    path("training/", views.training, name="training"),
    path("training/<str:trait>/", views.train_pet, name="train_pet"),
    path("shows/", views.shows, name="shows"),
    path("shows/enter/<int:show_id>/", views.enter_show, name="enter_show"),
    path("quests/", views.quests, name="quests"),
    path("quests/claim/<int:progress_id>/", views.claim_quest, name="claim_quest"),
    path("social/", views.social, name="social"),
    path("social/friend/<int:profile_id>/", views.send_friend_request, name="send_friend_request"),
    path("social/accept/<int:friendship_id>/", views.accept_friend_request, name="accept_friend_request"),
    path("social/block/<int:profile_id>/", views.block_profile, name="block_profile"),
    path("messages/", views.messages_inbox, name="messages_inbox"),
    path("messages/send/<int:profile_id>/", views.send_message, name="send_message"),
    path("chat/", views.chat, name="chat"),
    path("report/chat/<int:message_id>/", views.report_chat_message, name="report_chat_message"),
    path("support/", views.support, name="support"),
    path("rating/", views.rating, name="rating"),
]
