from django.contrib.auth import views as auth_views
from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("health/", views.health, name="health"),
    path("register/", views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("play/", views.dashboard, name="dashboard"),
    path("profile/", views.profile, name="profile"),
    path("settings/", views.settings, name="settings"),
    path("pets/new/", views.create_pet, name="create_pet"),
    path("pets/<int:pet_id>/select/", views.select_pet, name="select_pet"),
    path("pets/action/<str:action>/", views.pet_action, name="pet_action"),
    path("shop/", views.shop, name="shop"),
    path("shop/buy/<int:item_id>/", views.buy_item, name="buy_item"),
    path("shop/wearables/", views.wearable_shop, name="wearable_shop"),
    path("shop/wearables/buy/<int:wearable_id>/", views.buy_wearable, name="buy_wearable"),
    path("home-room/", views.home_room, name="home_room"),
    path("home-room/buy/<int:item_id>/", views.buy_furniture, name="buy_furniture"),
    path("home-room/place/<int:owned_id>/", views.place_furniture, name="place_furniture"),
    path("home-room/upgrade/<int:owned_id>/", views.upgrade_furniture, name="upgrade_furniture"),
    path("inventory/", views.inventory, name="inventory"),
    path("inventory/use/<int:inventory_id>/", views.use_item, name="use_item"),
    path("wardrobe/", views.wardrobe, name="wardrobe"),
    path("wardrobe/equip/<int:owned_id>/", views.equip_wearable, name="equip_wearable"),
    path("wardrobe/unequip/<int:equipped_id>/", views.unequip_wearable, name="unequip_wearable"),
    path("wardrobe/sell/<int:owned_id>/", views.sell_wearable, name="sell_wearable"),
    path("collections/", views.collections, name="collections"),
    path("trophies/", views.trophies, name="trophies"),
    path("explore/", views.explore, name="explore"),
    path("explore/<int:site_id>/", views.run_explore, name="run_explore"),
    path("training/", views.training, name="training"),
    path("training/<str:trait>/", views.train_pet, name="train_pet"),
    path("assistants/", views.assistants, name="assistants"),
    path("assistants/<int:assistant_id>/", views.train_assistant, name="train_assistant"),
    path("shows/", views.shows, name="shows"),
    path("shows/enter/<int:show_id>/", views.enter_show, name="enter_show"),
    path("quests/", views.quests, name="quests"),
    path("quests/claim/<int:progress_id>/", views.claim_quest, name="claim_quest"),
    path("social/", views.social, name="social"),
    path("social/friend/<int:profile_id>/", views.send_friend_request, name="send_friend_request"),
    path("social/accept/<int:friendship_id>/", views.accept_friend_request, name="accept_friend_request"),
    path("social/block/<int:profile_id>/", views.block_profile, name="block_profile"),
    path("messages/", views.messages_inbox, name="messages_inbox"),
    path("messages/send/<int:profile_id>/", views.send_message, name="send_message"),
    path("chat/", views.chat, name="chat"),
    path("report/chat/<int:message_id>/", views.report_chat_message, name="report_chat_message"),
    path("support/", views.support, name="support"),
    path("clubs/", views.clubs, name="clubs"),
    path("clubs/create/", views.create_club, name="create_club"),
    path("clubs/<int:club_id>/", views.club_detail, name="club_detail"),
    path("clubs/<int:club_id>/join/", views.request_club_join, name="request_club_join"),
    path("clubs/join-requests/<int:request_id>/accept/", views.accept_club_join, name="accept_club_join"),
    path("clubs/<int:club_id>/contribute/", views.contribute_club, name="contribute_club"),
    path("clubs/buildings/<int:building_id>/upgrade/", views.upgrade_club_building, name="upgrade_club_building"),
    path("clubs/<int:club_id>/announce/", views.post_club_announcement, name="post_club_announcement"),
    path("rating/", views.rating, name="rating"),
]
