# Generated by Django 5.2.1 on 2026-05-31 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('item_type', models.CharField(choices=[('food', 'Еда'), ('toy', 'Игрушка'), ('care', 'Уход')], max_length=16)),
                ('price', models.PositiveIntegerField()),
                ('energy_delta', models.IntegerField(default=0)),
                ('mood_delta', models.IntegerField(default=0)),
                ('hunger_delta', models.IntegerField(default=0)),
                ('experience_delta', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='spark', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=220)),
                ('action', models.CharField(choices=[('feed', 'Покормить'), ('play', 'Поиграть'), ('pet', 'Погладить'), ('walk', 'Прогулка'), ('buy', 'Покупка')], max_length=16)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('reward_experience', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('species', models.CharField(choices=[('cat', 'Котенок'), ('dog', 'Щенок'), ('bunny', 'Кролик'), ('fox', 'Лисенок')], default='cat', max_length=16)),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('energy', models.PositiveIntegerField(default=80)),
                ('mood', models.PositiveIntegerField(default=80)),
                ('hunger', models.PositiveIntegerField(default=70)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('profile', 'item')},
            },
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('count', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('claimed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to='game.playerprofile')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quest')),
            ],
            options={
                'unique_together': {('profile', 'quest', 'date')},
            },
        ),
    ]
