# Generated by Django 5.2.1 on 2026-05-31 21:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('first_feed', 'Первое кормление'), ('first_buy', 'Первая покупка'), ('level_3', 'Уровень 3'), ('three_pets', 'Команда питомцев'), ('rich', 'Копилка')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=180)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_energy_tick',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.pet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='game.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.achievement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('profile', 'achievement')},
            },
        ),
    ]
