# Generated by Django 5.2.1 on 2026-05-31 22:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_achievement_playerprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=220)),
                ('min_level', models.PositiveIntegerField(default=1)),
                ('entry_fee', models.PositiveIntegerField(default=0)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('reward_hearts', models.PositiveIntegerField(default=0)),
                ('reward_experience', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WearableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('slot', models.CharField(choices=[('outfit', 'Наряд'), ('collar', 'Ошейник'), ('hat', 'Шапка'), ('charm', 'Талисман'), ('background', 'Фон')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('beauty_bonus', models.PositiveIntegerField(default=0)),
                ('mood_bonus', models.PositiveIntegerField(default=0)),
                ('show_bonus', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#45b08c', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='beauty_delta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='hearts_delta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='agility',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='beauty',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pet',
            name='charm',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='obedience',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='hearts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quest',
            name='action',
            field=models.CharField(choices=[('feed', 'Покормить'), ('play', 'Поиграть'), ('pet', 'Погладить'), ('walk', 'Прогулка'), ('buy', 'Покупка'), ('train', 'Тренировка'), ('show', 'Выставка')], max_length=16),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=240)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='game.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='game.playerprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='game.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('medal', models.CharField(choices=[('bronze', 'Бронза'), ('silver', 'Серебро'), ('gold', 'Золото')], default='bronze', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_entries', to='game.pet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_entries', to='game.playerprofile')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='game.petshow')),
            ],
            options={
                'ordering': ['-score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=240)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.chatmessage')),
                ('reported_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='game.playerprofile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ActionCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('available_at', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooldowns', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('profile', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Друзья'), ('blocked', 'Заблокирован')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to='game.playerprofile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
        migrations.CreateModel(
            name='OwnedWearable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe', to='game.playerprofile')),
                ('wearable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.wearableitem')),
            ],
            options={
                'unique_together': {('profile', 'wearable')},
            },
        ),
        migrations.CreateModel(
            name='EquippedWearable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_wearables', to='game.pet')),
                ('wearable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.wearableitem')),
            ],
            options={
                'unique_together': {('pet', 'wearable')},
            },
        ),
    ]
