# Generated by Django 5.2.1 on 2026-06-01 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_petshow_wearableitem_item_beauty_delta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('role', models.CharField(choices=[('caretaker', 'Care'), ('stylist', 'Style'), ('scout', 'Explore'), ('builder', 'Home')], max_length=24)),
                ('base_cost', models.PositiveIntegerField(default=50)),
                ('max_level', models.PositiveIntegerField(default=20)),
                ('bonus_per_level', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('crest_color', models.CharField(default='#45b08c', max_length=16)),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('hearts', models.PositiveIntegerField(default=0)),
                ('member_limit', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubBuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('effect', models.CharField(choices=[('xp', 'XP'), ('club_xp', 'Club XP'), ('home', 'Home'), ('wardrobe', 'Wardrobe'), ('explore', 'Explore')], max_length=24)),
                ('bonus_per_level', models.PositiveIntegerField(default=1)),
                ('max_level', models.PositiveIntegerField(default=20)),
                ('base_cost', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('reward_hearts', models.PositiveIntegerField(default=0)),
                ('beauty_bonus', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExplorationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('min_level', models.PositiveIntegerField(default=1)),
                ('energy_cost', models.PositiveIntegerField(default=10)),
                ('coin_cost', models.PositiveIntegerField(default=0)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('reward_experience', models.PositiveIntegerField(default=0)),
                ('daily_limit', models.PositiveIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('slot', models.CharField(choices=[('bed', 'Bed'), ('toy_corner', 'Toy corner'), ('window', 'Window'), ('rug', 'Rug'), ('plant', 'Plant'), ('poster', 'Poster')], max_length=24)),
                ('price', models.PositiveIntegerField(default=0)),
                ('beauty_bonus', models.PositiveIntegerField(default=0)),
                ('xp_bonus_percent', models.PositiveIntegerField(default=0)),
                ('max_level', models.PositiveIntegerField(default=5)),
                ('color', models.CharField(default='#45b08c', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('trophy_type', models.CharField(choices=[('medal', 'Medal'), ('prize', 'Prize'), ('cup', 'Cup'), ('badge', 'Badge')], default='badge', max_length=16)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('beauty_bonus', models.PositiveIntegerField(default=0)),
                ('rarity', models.PositiveIntegerField(default=1)),
                ('color', models.CharField(default='#f3b84b', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ClubAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.playerprofile')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='game.club')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(default=0)),
                ('hearts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='game.club')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_contributions', to='game.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.playerprofile')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='game.club')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=1)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='game.collectionset')),
            ],
            options={
                'ordering': ['collection', 'order'],
                'unique_together': {('collection', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ExplorationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.collectionpiece')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.pet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explorations', to='game.playerprofile')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.explorationsite')),
                ('found_trophy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.trophy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.club')),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.clubbuildingtype')),
            ],
            options={
                'unique_together': {('club', 'building_type')},
            },
        ),
        migrations.CreateModel(
            name='ClubJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='game.club')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_join_requests', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('club', 'profile', 'status')},
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('deputy', 'Deputy'), ('officer', 'Officer'), ('member', 'Member')], default='member', max_length=16)),
                ('contribution_score', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='game.club')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('club', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='CompletedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.collectionset')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_collections', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('profile', 'collection')},
            },
        ),
        migrations.CreateModel(
            name='OwnedCollectionPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.collectionpiece')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_pieces', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('profile', 'piece')},
            },
        ),
        migrations.CreateModel(
            name='OwnedFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('placed', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.furnitureitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('profile', 'item')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('assistant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.assistanttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('profile', 'assistant_type')},
            },
        ),
        migrations.CreateModel(
            name='OwnedTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='game.playerprofile')),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.trophy')),
            ],
            options={
                'unique_together': {('profile', 'trophy')},
            },
        ),
    ]
