# Generated by Django 5.2.1 on 2026-06-01 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_assistanttype_club_clubbuildingtype_collectionset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('min_level', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('energy_cost', models.PositiveIntegerField(default=10)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('reward_hearts', models.PositiveIntegerField(default=0)),
                ('reward_experience', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('key_cost', models.PositiveIntegerField(default=1)),
                ('daily_limit', models.PositiveIntegerField(default=3)),
                ('min_coins', models.PositiveIntegerField(default=10)),
                ('max_coins', models.PositiveIntegerField(default=50)),
                ('color', models.CharField(default='#f3b84b', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('stat', models.CharField(choices=[('agility', 'Agility'), ('charm', 'Charm'), ('mood', 'Mood')], max_length=16)),
                ('min_level', models.PositiveIntegerField(default=1)),
                ('entry_fee', models.PositiveIntegerField(default=0)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('reward_hearts', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FragmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('garden', 'Garden'), ('jewel', 'Jewel')], max_length=16)),
                ('required_fragments', models.PositiveIntegerField(default=5)),
                ('beauty_bonus', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#45b08c', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('price_hearts', models.PositiveIntegerField(default=5)),
                ('color', models.CharField(default='#ef7b6a', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=2000)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChestOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_text', models.CharField(max_length=160)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('hearts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chest_openings', to='game.playerprofile')),
                ('chest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.chesttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('league', models.CharField(default='Sprout', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='game.pet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='game.playerprofile')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='game.competitionmode')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=180)),
                ('is_news', models.BooleanField(default=False)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_categories', to='game.club')),
            ],
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('pinned', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.playerprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='game.forumcategory')),
            ],
            options={
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1200)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.playerprofile')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='game.forumthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compact_mode', models.BooleanField(default=False)),
                ('show_bottom_nav', models.BooleanField(default=True)),
                ('show_quick_actions', models.BooleanField(default=True)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('low_bandwidth', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PetAdventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finishes_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='game.pet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='game.playerprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.adventureroute')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SentGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.giftcatalogitem')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to='game.playerprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to='game.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnedFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('fragment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.fragmenttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='game.playerprofile')),
            ],
            options={
                'unique_together': {('profile', 'fragment_type')},
            },
        ),
    ]
