# Generated by Django 5.2.1 on 2026-06-01 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_adventureroute_chesttype_competitionmode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, unique=True)),
                ('description', models.CharField(max_length=220)),
                ('theme', models.CharField(choices=[('care', 'Забота'), ('explore', 'Исследование'), ('style', 'Стиль'), ('social', 'Дружба')], default='care', max_length=20)),
                ('energy_cost', models.PositiveIntegerField(default=8)),
                ('coin_cost', models.PositiveIntegerField(default=0)),
                ('reward_coins', models.PositiveIntegerField(default=20)),
                ('reward_hearts', models.PositiveIntegerField(default=1)),
                ('reward_experience', models.PositiveIntegerField(default=10)),
                ('bond_delta', models.PositiveIntegerField(default=12)),
                ('heart_boost_cost', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['theme', 'title'],
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='bond',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='action',
            field=models.CharField(choices=[('feed', 'Покормить'), ('play', 'Поиграть'), ('pet', 'Погладить'), ('walk', 'Прогулка'), ('buy', 'Покупка'), ('train', 'Тренировка'), ('show', 'Выставка'), ('memory', 'Тропа памяти')], max_length=16),
        ),
        migrations.CreateModel(
            name='MemoryChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=120)),
                ('story', models.TextField(max_length=900)),
                ('reward_coins', models.PositiveIntegerField(default=0)),
                ('reward_hearts', models.PositiveIntegerField(default=0)),
                ('reward_experience', models.PositiveIntegerField(default=0)),
                ('bond_delta', models.PositiveIntegerField(default=0)),
                ('boosted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_chapters', to='game.pet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_chapters', to='game.playerprofile')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='game.memoryprompt')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'date'), name='unique_daily_memory_chapter')],
            },
        ),
    ]
