# Generated by Django 5.2.1 on 2026-06-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_memoryprompt_pet_bond_alter_quest_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='supabase_user_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
