# Generated by Django 5.2.1 on 2026-06-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_playerprofile_supabase_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistanttype',
            name='role',
            field=models.CharField(choices=[('caretaker', 'Забота'), ('stylist', 'Стиль'), ('scout', 'Исследования'), ('builder', 'Дом')], max_length=24),
        ),
        migrations.AlterField(
            model_name='clubbuildingtype',
            name='effect',
            field=models.CharField(choices=[('xp', 'Опыт'), ('club_xp', 'Опыт клуба'), ('home', 'Дом'), ('wardrobe', 'Гардероб'), ('explore', 'Исследования')], max_length=24),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('deputy', 'Заместитель'), ('officer', 'Офицер'), ('member', 'Участник')], default='member', max_length=16),
        ),
        migrations.AlterField(
            model_name='competitionmode',
            name='stat',
            field=models.CharField(choices=[('agility', 'Ловкость'), ('charm', 'Шарм'), ('mood', 'Настроение')], max_length=16),
        ),
        migrations.AlterField(
            model_name='fragmenttype',
            name='kind',
            field=models.CharField(choices=[('garden', 'Сад'), ('jewel', 'Самоцвет')], max_length=16),
        ),
        migrations.AlterField(
            model_name='furnitureitem',
            name='slot',
            field=models.CharField(choices=[('bed', 'Лежанка'), ('toy_corner', 'Уголок игрушек'), ('window', 'Окно'), ('rug', 'Ковер'), ('plant', 'Растение'), ('poster', 'Постер')], max_length=24),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='trophy_type',
            field=models.CharField(choices=[('medal', 'Медаль'), ('prize', 'Приз'), ('cup', 'Кубок'), ('badge', 'Значок')], default='badge', max_length=16),
        ),
    ]
